blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://github.com/Bonsailinse/axobotl/discussions
    about: Ask the community for support
  - name: Get help on Discord
    url: https://discord.gg/TynN4mjajp
    about: Have a quick question? Join the Discord server and ask on the appropriate channel.